### ISSUE TITLE
Long time to run in personal PC, could you provide the transformed CSV for downloading?

### ISSUE THREAD

**Issue by momo1986** [SajjadMzf/NGSIM2HIGHD#1]
Have some problem to run the program.
Is there the possibility to share the transformed CSV files?

Thanks & Regards!

**Comment by SajjadMzf** [comment]
Hi,

I am afriad I might not  be allowed to share transformed files.

This work is currently in progress. few bugs need to be addressed.

**Comment by chenhengwei1999** [comment]
Hi, Author. Is this source code fixed now?

Looking forward to your reply. Thanks.

**Comment by SajjadMzf** [comment]
Hello,
The code is used to create a more comprehensive trajectory data preprocessing here:https://github.com/SajjadMzf/TrajPreprocess/tree/b683fb8b27800e0202417865e05e192e7647cfa6
