### ISSUE TITLE
HighDtoNGSIM 

### ISSUE THREAD

**Issue by AI-lab-sh** [SajjadMzf/NGSIM2HIGHD#2]
hello
I have a question. can we do it vice versa? converting highD to NGSIM? do you have any hint about how to modify preprocess code of NGSIM to work correctly on highD dataset ?

**Comment by SajjadMzf** [comment]
Hello,
Following repository might be helpful. You may use some pre-defined functions and the framework to implement what you need.
https://github.com/SajjadMzf/TrajPreprocess/tree/b683fb8b27800e0202417865e05e192e7647cfa6
